import type { V2Content } from '@/app/(he)/(site)/content'

export const EN_SERVICE_SLUGS = [
  'web-development',
  'seo',
  'development',
  'ecommerce',
  'brochure',
  'marketing',
  'branding',
  'maintenance',
  'ai-agents',
  'ai-search',
] as const

export const contentEn: Partial<V2Content> = {
  header: {
    brand: 'AITERRA',
    navLabel: 'Main navigation',
    mobileNavLabel: 'Mobile navigation',
    menuOpen: 'Menu',
    menuClose: 'Close menu',
    expand: 'Expand',
    collapse: 'Collapse',
    cta: { label: 'Get a quote', href: '/en/contact' },
    nav: [
      {
        id: 'services',
        label: 'Services',
        href: '/en/services',
        submenu: 'services',
        overviewLabel: 'All services',
      },
      { id: 'blog', label: 'Blog', href: '/en/blog' },
      {
        id: 'portfolio',
        label: 'Work',
        href: '/en/projects',
        submenu: 'portfolio',
        overviewLabel: 'All work',
      },
      { id: 'about', label: 'About the agency', href: '/en/about' },
      { id: 'lang', label: 'עברית', href: '/', flag: 'il' },
    ],
  },

  hero: {
    headline: ['Custom web development', 'and SEO agency'],
    tags: ['Engineering', 'SEO', 'Platforms', 'Growth'],
    lede: [
      'We design and build custom websites, web platforms and internal tools in code,',
      'then rank them - the same team writes the software and owns the organic growth.',
    ],
    primaryAction: { label: 'Start a project', href: '/en/contact' },
    secondaryAction: { label: 'See our services', href: '/en/services' },
  },

  heroProjects: [
    {
      id: 'olie',
      label: 'Olie 6',
      href: '/en/projects',
      surface: '#e6ecf8',
      shot: '/images/portfolio/tiles/olie-6.webp',
    },
    {
      id: 'neot-sade',
      label: 'Neot Sade',
      href: '/en/projects',
      surface: '#f4e8d2',
      shot: '/images/portfolio/tiles/neot-sade.webp',
    },
    {
      id: 'hofit',
      label: 'Hofit Cosmetics',
      href: '/en/projects',
      surface: '#e2ece0',
      shot: '/images/portfolio/tiles/hofit-cosmetics.webp',
    },
    {
      id: 'karin-cohen',
      label: 'Karin Cohen',
      href: '/en/projects',
      surface: '#ece2f3',
      shot: '/images/portfolio/tiles/karin-cohen.webp',
    },
    {
      id: 'brand-identity',
      label: 'Brand identity',
      href: '/en/projects',
      surface: '#f7ded6',
      shot: '/images/portfolio/tiles/brand-identity.webp',
    },
  ],

  heroRails: {
    projectsTitle: 'Selected work',
    projectsAdvance: 'Next project',
    topicsTitle: 'Technologies and disciplines we specialise in',
    topicsAdvance: 'More disciplines',
  },

  heroTopics: [
    'Custom development',
    'Organic search',
    'Web platforms',
    'Business automation',
    'API integrations',
    'Technical SEO',
    'Headless architecture',
    'Web applications',
    'eCommerce',
    'Core Web Vitals',
    'UI/UX design',
    'Generative engine optimisation',
  ],

  about: {
    eyebrow: 'ABOUT Aiterra',
    heading: ['Engineering, design and search', 'without juggling five vendors.'],
    lede: 'Most digital projects break in the handoffs: the agency that designs it cannot build it, the developer who builds it cannot rank it, and the SEO consultant files tickets nobody picks up. We keep all of it in one team.',
    outro: 'Our team is ready to take your digital presence forward. Are you?',
    action: { label: 'Scope your project', href: '/en/contact' },
  },

  aboutRoles: [
    {
      id: 'project-manager',
      title: 'Project lead',
      art: '/images/about-card4.webp',
      text: 'One person who owns the timeline, coordinates every specialist and keeps the project on schedule and on budget. You never chase status updates.',
    },
    {
      id: 'marketing',
      title: 'Growth and strategy',
      art: '/images/about-card3.webp',
      text: 'We connect positioning, audience and messaging so the site and the campaigns behind it pull in the same direction instead of competing.',
    },
    {
      id: 'build',
      title: 'Engineers and designers',
      art: '/images/about-card2.webp',
      text: 'UX and custom development built together, so the product looks right and loads fast on the devices your customers actually use.',
    },
    {
      id: 'seo',
      title: 'SEO engineers',
      art: '/images/about-card1.webp',
      text: 'Organic search handled at the code level. When a technical issue blocks rankings, the people who can fix it sit in the same room.',
    },
  ],

  stats: {
    heading: ['The engineering is the method.', 'The business result is the point.'],
    lede: 'We work in a modern stack - Next.js, React and TypeScript - and judge every project against numbers rather than impressions: load time, stability over time and the conversion rate you actually get.',
  },

  statItems: [
    {
      id: 'campaigns',
      value: '50+',
      label: 'Campaigns running',
      text: 'Campaigns we manage and measure continuously as part of our clients marketing, not set-and-forget launches.',
    },
    {
      id: 'clients',
      value: '75+',
      label: 'Business owners served',
      text: 'Owners who took a step forward and grew the traffic their business gets, with us.',
    },
    {
      id: 'uptime',
      value: '100%',
      label: 'Stable services',
      text: 'Infrastructure built to stay up, fast and stable as the business keeps growing.',
    },
    {
      id: 'performance',
      value: '95+',
      label: 'Performance score',
      text: 'Speed and load performance handled inside the development process, not patched on at the end.',
    },
  ],

  services: {
    lead: {
      text: 'Let us turn these numbers into results for your business',
      action: { label: 'Scope your project', href: '/en/contact' },
    },
    eyebrow: 'OUR SERVICES',
    heading: ['Everything your business needs online.'],
    lede: 'Discovery, design, engineering, organic search and paid media - every stage of building your digital presence sits with one team and one project lead, from the first call through launch and beyond.',
  },

  serviceTabs: [
    {
      id: 'web-development',
      label: 'Web development',
      tags: [
        'Discovery and scoping',
        'UX/UI design',
        'Next.js and React',
        'Headless architecture',
        'Core Web Vitals',
        'Accessibility',
      ],
      question: 'What is different about how we build?',
      paragraphs: [
        'We build in code rather than fighting the limits of a theme and a stack of plugins. That means the information architecture, the integrations and the buyer journey follow your business logic instead of a template author’s assumptions.',
        'Performance is measured during development, not patched at the end. A slow site burns paid budget and loses visitors before they ever read the offer.',
      ],
      action: { label: 'Custom web development', href: '/en/services/web-development' },
    },
    {
      id: 'seo',
      label: 'SEO',
      tags: [
        'Keyword research',
        'Technical SEO',
        'Content strategy',
        'Digital PR',
        'Local search',
        'AI search visibility',
      ],
      question: 'What is different about how we rank sites?',
      paragraphs: [
        'The team that ranks your site also writes its code. A technical blocker - render-blocking scripts, broken schema, a bad URL structure - gets fixed in the repository this sprint instead of sitting in another vendor’s backlog for a quarter.',
        'We report on qualified enquiries, not just positions. Rankings that do not produce pipeline are a vanity metric.',
      ],
      action: { label: 'SEO and website promotion', href: '/en/services/seo' },
    },
    {
      id: 'development',
      label: 'Custom platforms',
      tags: [
        'Web applications',
        'Customer portals',
        'Dashboards',
        'Business automation',
        'API integrations',
        'Internal tools',
      ],
      question: 'What is different about our platform work?',
      paragraphs: [
        'We build the systems that off-the-shelf software cannot cover: portals with role-based access, operational dashboards, workflow automation and the integrations that move data between them reliably.',
        'Every platform is designed to be extended. Growth should mean adding a module, not commissioning a rewrite.',
      ],
      action: { label: 'Custom web platforms', href: '/en/services/development' },
    },
    {
      id: 'ecommerce',
      label: 'Online stores',
      tags: [
        'Custom storefront',
        'Checkout and payments',
        'Israeli invoicing',
        'Inventory and orders',
        'Mobile conversion',
        'Store migration',
      ],
      question: 'What is different about the stores we build?',
      paragraphs: [
        'A store is judged on the checkout, not the homepage. We build the catalogue, the cart and the payment flow in code, and connect them to the card clearing and invoicing providers you already use, so an order produces a payment and a valid invoice without anyone re-keying it.',
        'The failure mode we design against is the silent one: a broken hand-off where orders keep arriving and invoices quietly stop. Monitoring catches it before your accountant does.',
      ],
      action: { label: 'Online store development', href: '/en/services/ecommerce' },
    },
    {
      id: 'branding',
      label: 'Branding',
      tags: [
        'Brand strategy',
        'Logo design',
        'Visual language',
        'Brand guidelines',
        'Tone of voice',
        'Sales collateral',
      ],
      question: 'What is different about our branding work?',
      paragraphs: [
        'Branding here starts with who the customer is and what they need to remember, and only then arrives at colours and typefaces. A palette chosen before that question is decoration, not positioning.',
        'The result is one language that holds up on the site, in the campaign and at every other point of contact - and it is made by the team that also has to build it, so nothing in the guidelines is undeliverable.',
      ],
      action: { label: 'Branding and design', href: '/en/services/branding' },
    },
    {
      id: 'brochure',
      label: 'Brochure sites',
      tags: [
        'Positioning and structure',
        'UX and UI design',
        'Conversion copy',
        'Mobile performance',
        'Enquiry capture',
        'Analytics from day one',
      ],
      question: 'What is different about our brochure sites?',
      paragraphs: [
        'A brochure site is not a digital leaflet. It is the first impression the business makes, so it is built around the message rather than around a template, and each page leads to the next thing you want the visitor to do.',
        'The pages answer objections in the order a prospect actually raises them - services, process, proof, pricing - so the site does part of the qualifying before anyone picks up the phone.',
      ],
      action: { label: 'Brochure site development', href: '/en/services/brochure' },
    },
    {
      id: 'marketing',
      label: 'Paid media',
      tags: [
        'Google Ads',
        'Meta campaigns',
        'Landing pages',
        'Creative production',
        'Conversion tracking',
        'Budget management',
      ],
      question: 'What is different about how we run campaigns?',
      paragraphs: [
        'The ad, the page it lands on and the tracking behind it are built by the same team, so campaign spend does not land on a homepage that was never designed to convert it.',
        'Campaigns are planned around the stage your business is actually at rather than a template media plan, and measured against enquiries rather than impressions.',
      ],
      action: { label: 'Campaign management', href: '/en/services/marketing' },
    },
    {
      id: 'maintenance',
      label: 'Maintenance',
      tags: [
        'Security updates',
        'Daily backups',
        'Uptime monitoring',
        'Content changes',
        'Integration upkeep',
        'Monthly report',
      ],
      question: 'What does maintenance cover?',
      paragraphs: [
        'Monthly plans with published pricing and response times written into the agreement rather than promised, including for sites we did not build ourselves.',
        'Payment and invoicing connections are checked continuously, because when one breaks nothing on the site looks wrong: orders keep arriving and invoices simply stop being created.',
      ],
      action: { label: 'Website maintenance', href: '/en/services/maintenance' },
    },
    {
      id: 'ai-agents',
      label: 'AI agents',
      tags: [
        'Round-the-clock replies',
        'Lead qualification',
        'Meeting booking',
        'CRM connection',
        'WhatsApp',
        'Human handoff',
      ],
      question: 'What is different about the AI agents we build?',
      paragraphs: [
        'The agent answers from your own pricing, terms and catalogue rather than from the model general knowledge, and when a question has no source behind it the defined answer is that it does not know - a price it invents is a commitment made in your name.',
        'It also acts rather than only replying: opening a lead, booking a meeting and updating a status in the systems you already run, so nobody is left copying details across by hand at the end of the day.',
      ],
      action: { label: 'AI agent development', href: '/en/services/ai-agents' },
    },
    {
      id: 'ai-search',
      label: 'AI search',
      tags: [
        'AI Overviews',
        'ChatGPT and Gemini',
        'Entity definition',
        'Structured data',
        'Quotable content',
        'Visibility report',
      ],
      question: 'What is different about how we work on AI search?',
      paragraphs: [
        'An answer written by an engine has no first place - there is a source it cited and a source it did not. So the work starts with entity and schema rather than with content: an engine does not cite a business it is unsure exists.',
        'Measurement changes with it. A fixed set of real questions is run every month to record whether you were named, in what context and alongside whom, instead of tracking positions that do not exist there.',
      ],
      action: { label: 'AI search visibility', href: '/en/services/ai-search' },
    },
  ],

  allIn: {
    eyebrow: 'ALL-IN-ONE',
    heading: ['Engineering, the website and growth', 'have to work as one system'],
  },

  allInNodes: [
    {
      id: 'discovery',
      label: 'Discovery',
      side: 'left',
      x: '21.4%',
      y: '54.2%',
      edge: '9%',
      mobile: { x: '73.4%', y: '67.3%', place: 'bottom', len: '96px' },
    },
    {
      id: 'marketing',
      label: 'Growth',
      side: 'right',
      x: '70.5%',
      y: '54.2%',
      edge: '89.2%',
      mobile: { x: '72.5%', y: '37.5%', place: 'top', len: '96px' },
    },
    {
      id: 'creative',
      label: 'Content',
      side: 'left',
      x: '24.4%',
      y: '69.7%',
      edge: '8.7%',
      mobile: { x: '50%', y: '73.4%', place: 'bottom', len: '52px' },
    },
    {
      id: 'design',
      label: 'Design',
      side: 'right',
      x: '82.5%',
      y: '69.7%',
      edge: '92.8%',
      mobile: { x: '50%', y: '29.7%', place: 'top', len: '56px' },
    },
    {
      id: 'seo',
      label: 'SEO',
      side: 'left',
      x: '22.2%',
      y: '85.5%',
      edge: '8.7%',
      mobile: { x: '26.6%', y: '67.3%', place: 'bottom', len: '96px' },
    },
    {
      id: 'development',
      label: 'Engineering',
      side: 'right',
      x: '84%',
      y: '80.9%',
      edge: '93.8%',
      mobile: { x: '27.5%', y: '37.5%', place: 'top', len: '96px' },
    },
  ],

  faq: {
    heading: ['Before we start', 'a few things worth knowing.'],
  },

  faqEntries: [
    {
      id: 'cost',
      question: 'How much does a custom website cost to build?',
      answer:
        'Pricing follows scope rather than page count. A focused landing page, a full marketing site, and a custom platform with authentication and integrations sit in three separate brackets. What actually moves the number is usually the integration work - Israeli card clearing, invoicing through Morning, Greeninvoice or iCount, a CRM connection, inventory management - rather than the volume of text or the number of pages, since twenty pages running on three templates is far less work than five pages that each look different. After a short discovery call you receive a written quote stating exactly what is included, what is excluded and what would count as an addition. Nothing surfaces halfway through the build that was not on that document, and you can compare it against a competing proposal on the same terms.',
    },
    {
      id: 'timeline',
      question: 'How long does it take to build a custom website?',
      answer:
        'A landing page ships in a few weeks. A full marketing site typically runs one to two months from the moment the specification is approved. An online store with a catalogue, card clearing and an invoicing connection runs one to three months, and a custom platform with user permissions and real business logic takes longer than either. In practice the schedule is set by content, photography and client approvals far more often than by engineering time, which is why we lock those during discovery rather than chasing them mid-build. Projects that arrive with their content ready almost always finish on schedule. We deliver in increments you can click through, so corrections land early instead of in the last week before launch.',
    },
    {
      id: 'template-vs-custom',
      question: 'What is the difference between custom web development and a website template?',
      answer:
        'A template forces your content, navigation and workflows into layouts someone else designed for a generic business. Custom development inverts that: the structure follows how your business actually sells and operates. The practical differences show up in three places. Page speed, because a template carries markup and scripts for features you will never use, and Core Web Vitals feed directly into Google rankings. Integration, because connecting cleanly to your CRM and back office is straightforward in code and a plugin problem otherwise. And the day you need a feature the template author never anticipated - that is where the template tax is actually paid, in workarounds that cost more each year than building it properly once. Every plugin is also a security and update dependency.',
    },
    {
      id: 'ownership',
      question: 'Do we own the code after the project is delivered?',
      answer:
        'Yes. At handover you receive the code repository, the deployment pipeline to the server, and credentials for every connected service: hosting, domain, payment processing, invoicing and analytics. Design source files and brand assets are handed over too. We do not retain clients through technical lock-in, so if you decide to continue with another partner the transition is documented and does not require rebuilding the site from scratch. That is the practical difference from closed platforms such as Wix or Shopify, where the content and the design are yours but the system running them is not. It is worth confirming this clause appears in writing in any proposal you are weighing, ours included, because the absence of it is itself information.',
    },
    {
      id: 'seo-timeline',
      question: 'How long does SEO take to show results?',
      answer:
        'Early signals - improved indexation, rising impressions and movement on lower-competition terms - usually appear within two to four months. Meaningful gains on competitive commercial terms typically take six months or more, and longer in saturated categories. A brand new domain starts slower than an established site with existing authority, and the technical state of the site changes the answer again: a site that is not being crawled properly will not rank even excellent content. We measure progress in the Google Search Console and GA4 accounts you own, and in the first months we report on impressions and indexation - the metrics that actually move first - rather than only on enquiries. Anyone promising faster than this is describing an outcome they do not control.',
    },
    {
      id: 'seo-vs-ads',
      question: 'Should we invest in SEO or paid ads?',
      answer:
        'Paid search delivers traffic on day one and stops the moment the budget does - it buys exposure rather than building an asset. Organic search takes months to compound but keeps producing enquiries after the spend pauses, and reaches people who are still researching rather than ready to buy. The difference shows up in unit economics: with paid, cost per lead stays roughly flat over time; with organic, it falls as the content accumulates authority. For most businesses the answer is both, weighted by stage - paid to validate demand and messaging quickly and to gather market data, organic running in parallel as the asset that lowers acquisition cost over the following year. What you should not do is judge either channel without conversion tracking in place.',
    },
    {
      id: 'ai-search',
      question: 'Will our site show up in AI Overviews and ChatGPT answers?',
      answer:
        'That work is called generative engine optimisation, and we treat it as part of the SEO engagement rather than an upsell. In practice it requires four things. Content that answers questions directly, self-containedly and with enough concrete fact that a whole passage can be quoted without surrounding context. Valid structured data in JSON-LD, including published prices, FAQ entries and organisation details. Authority and brand mentions across sources these systems already trust, since a model draws on what others write about you and not only on what you write about yourself. And crawler access configured deliberately in robots.txt and llms.txt rather than left to chance. It matters because a growing share of searches now end in an answer rather than a click to any website.',
    },
    {
      id: 'integrations',
      question: 'Can you integrate with our CRM, ERP and payment systems?',
      answer:
        'Yes, and it is usually the reason clients come to us. We build API integrations between the site and the tools you already run: accounting and invoicing through Morning (Green Invoice), Greeninvoice, iCount, Rivhit, Hashavshevet or Priority; CRM systems such as Fireberry and Powerlink; plus Israeli card clearing, shipping providers, email and the WhatsApp Business API. Leads, orders, invoices and inventory then move automatically instead of being retyped between systems. During discovery we settle which fields move, in which direction, how often, and what happens on error - because the important question in an integration is not what happens when everything works, but what happens when a provider is unavailable or returns something unexpected. Where an integration is genuinely not feasible, we say so before the contract is signed.',
    },
    {
      id: 'existing-site',
      question: 'We already have a website. Can you improve it instead of rebuilding?',
      answer:
        'Often, yes, and it is a technical question rather than a matter of taste. Discovery starts by establishing what is worth keeping - content that ranks, URL structure, inbound links and existing organic positions - alongside a crawl of the site, a speed and Core Web Vitals check, and its indexing status in Google Search Console. If an upgrade solves the problem we will say so, because it costs less and preserves the history you have already earned. Where a rebuild is the right call, we plan the 301 redirect map before anything moves, preserve heading structure and metadata, and monitor coverage and rankings after launch. An unplanned migration off an established site is one of the fastest ways to erase years of search equity, and the cause is almost always URLs that changed without a redirect.',
    },
    {
      id: 'support',
      question: 'What happens after launch?',
      answer:
        'Launch is the start of the engagement, not the end of it. We monitor performance and uptime, ship security and dependency updates, run daily off-server backups, keep improving the pages that carry commercial weight, and track behaviour in GA4 and Google Search Console. The first few weeks almost always surface refinements that only real use exposes - a form that should be shorter, a message that is not landing, a missing field - and those are handled as part of the engagement rather than reopened as a new project. You get a clear monthly report and one named point of contact who knows the build. Ongoing maintenance is available as a monthly plan with published pricing and a response time written into the agreement.',
    },
  ],

  partners: {
    caption: 'Platforms and technologies we specialise in',
    logos: [
      { name: 'Next.js', src: '/icons/tech/nextjs.svg', scale: 0.9 },
      { name: 'React', src: '/icons/tech/react.svg', scale: 0.95 },
      { name: 'React Native', src: '/icons/tech/react-native.svg', scale: 0.9 },
      { name: 'TypeScript', src: '/icons/tech/typescript.svg', scale: 0.9 },
      { name: 'Tailwind CSS', src: '/icons/tech/tailwindcss.svg', scale: 0.95 },
      { name: 'Vite', src: '/icons/tech/vite.svg', scale: 0.9 },
      { name: 'Three.js', src: '/icons/tech/threejs.svg', scale: 0.85 },
      { name: 'Node.js', src: '/icons/tech/nodejs.svg', scale: 0.95 },
      { name: 'FastAPI', src: '/icons/tech/fastapi.svg', scale: 0.9 },
      { name: 'Python', src: '/icons/tech/python.svg', scale: 0.95 },
      { name: 'Prisma', src: '/icons/tech/prisma.svg', scale: 0.9 },
      { name: 'PostgreSQL', src: '/icons/tech/postgresql.svg', scale: 0.95 },
      { name: 'MongoDB', src: '/icons/tech/mongodb.svg', scale: 0.95 },
      { name: 'Docker', src: '/icons/tech/docker.svg', scale: 0.95 },
      { name: 'GitHub Actions', src: '/icons/tech/githubactions.svg', scale: 0.85 },
      { name: 'AWS', src: '/icons/tech/aws.svg', scale: 0.9 },
      { name: 'Cloudflare', src: '/icons/tech/cloudflare.svg', scale: 0.95 },
      { name: 'Figma', src: '/icons/tech/figma.svg', scale: 0.9 },
      { name: 'Google Analytics', src: '/icons/tech/googleanalytics.svg', scale: 0.9 },
      { name: 'Google Tag Manager', src: '/icons/tech/googletagmanager.svg', scale: 0.9 },
    ],
  },

  contact: {
    heading: ['Let us build', 'your next project.'],
    art: {
      src: '/images/form.webp',
      caption: ["Let's kick off", 'your project'],
    },
    title: 'Tell us about it',
    fields: {
      name: 'Full name',
      phone: 'Phone',
      email: 'Email',
      service: 'Service',
      servicePlaceholder: 'Select a service',
      message: 'What do you want to build, improve or solve?',
    },
    serviceOther: 'Other',
    consent: {
      before: 'I have read and agree to the ',
      terms: { label: 'terms of use', href: '/en/terms-of-use' },
      joiner: ' and the ',
      privacy: { label: 'privacy policy', href: '/en/privacy-policy' },
      after: '.',
    },
    submit: 'Request a free consultation',
    sending: 'Sending…',
    success: {
      title: 'Thank you - we have your enquiry.',
      text: 'We will get back to you shortly to arrange an introductory call.',
    },
    error: 'Something went wrong. Please try again, or email us at info@aiterra.co.il',
  },

  footer: {
    brand: 'AITERRA',
    columns: [
      {
        id: 'services',
        title: 'Services',
        links: [
          { label: 'Custom web development', href: '/en/services/web-development' },
          { label: 'SEO and website promotion', href: '/en/services/seo' },
          { label: 'Online stores', href: '/en/services/ecommerce' },
          { label: 'Custom web platforms', href: '/en/services/development' },
          { label: 'Business websites', href: '/en/services/brochure' },
          { label: 'Paid campaigns', href: '/en/services/marketing' },
          { label: 'Brand and UX/UI', href: '/en/services/branding' },
          { label: 'Website maintenance', href: '/en/services/maintenance' },
          { label: 'AI agents', href: '/en/services/ai-agents' },
          { label: 'AI search visibility', href: '/en/services/ai-search' },
          { label: 'All services', href: '/en/services' },
        ],
      },
      {
        id: 'general',
        title: 'Company',
        links: [
          { label: 'About the agency', href: '/en/about' },
          { label: 'Our work', href: '/en/projects' },
          { label: 'Contact', href: '/en/contact' },
          { label: 'Hebrew site', href: '/' },
        ],
      },
    ],
    contactTitle: 'Get in touch',
    socialLabels: { instagram: 'Instagram', facebook: 'Facebook' },
    legal: [
      { label: 'Accessibility statement', href: '/en/accessibility-statement' },
      { label: 'Terms of use', href: '/en/terms-of-use' },
      { label: 'Privacy policy', href: '/en/privacy-policy' },
    ],
    copyright: 'Copyright ©Aiterra. All rights reserved',
  },

  portfolio: {
    eyebrow: 'SELECTED WORK',
    heading: ['A look at some of the projects', 'we have shipped'],
    lede: 'Online stores, lead-generating sites, internal systems and brand work. Each project below had a defined commercial goal before a line of code was written, and each one is live today.',
    cardAction: 'Visit the site',
    prev: 'Previous project',
    next: 'Next project',
    outro: 'Like what you see? Take a look at the rest of the work.',
    action: { label: 'See all our work', href: '/en/projects' },
  },

  article: {
    tocTitle: 'Contents',
    authorLabel: 'Written by',
    share: 'Share',
    copied: 'Link copied',
    publishedPrefix: 'Published',
    promoLabel: 'Let us work together',
    relatedTitle: 'More articles you might find useful',
    prev: 'Previous articles',
    next: 'More articles',
  },

  projectPage: {
    crumbHome: 'Home',
    crumb: 'Work',
    readMore: 'Read more',
    visit: 'Visit the site',
    aboutEyebrow: 'BACKGROUND',
    aboutHeading: 'About the project',
    factDate: 'Date',
    factField: 'Field',
    factType: 'Project type',
    factTech: 'Technology',
    challengeEyebrow: 'THE CHALLENGE',
    challengeHeading: 'What was the challenge?',
    solutionEyebrow: 'OUR SOLUTION',
    solutionHeading: 'Our solution',
    moreEyebrow: 'MORE PROJECTS',
    moreHeading: 'More projects',
    shotAlt: 'Screenshot of the site',
  },

  projectBanner: {
    heading: 'Let us ship your project',
    action: { label: 'Talk to us and we will scope it', href: '/en/contact' },
  },

  portfolioFilters: [
    { id: 'all', label: 'All' },
    { id: 'sales', label: 'Online stores' },
    { id: 'brand', label: 'Brand and leads' },
    { id: 'systems', label: 'Systems' },
  ],

  portfolioItems: [
    {
      id: 'neot-sade',
      title: 'Neot Sade — grocery delivery store',
      tags: ['Next.js', 'eCommerce', 'Payments', 'Loyalty club'],
      shot: '/images/portfolio/cards/neot-sade.webp',
      href: '/en/projects/neot-sade',
      category: 'sales',
    },
    {
      id: 'alova',
      title: 'ALOVA — hair care store',
      tags: ['Shopify', 'Online store', 'UI/UX'],
      shot: '/images/portfolio/cards/alova.webp',
      href: '/en/projects/alova',
      category: 'sales',
    },
    {
      id: 'olie-6',
      title: 'Olie 6 — olive oil store',
      tags: ['Shopify', 'eCommerce', 'UI/UX'],
      shot: '/images/portfolio/cards/olie-6.webp',
      href: '/en/projects/olie-6',
      category: 'sales',
    },
    {
      id: 'hofit-cosmetics',
      title: 'Hofit Cosmetics — treatment booking',
      tags: ['Landing page', 'UI/UX', 'Lead capture', 'WhatsApp'],
      shot: '/images/portfolio/cards/hofit-cosmetics.webp',
      href: '/en/projects/hofit-cosmetics',
      category: 'sales',
    },
    {
      id: 'sous-chef',
      title: 'Sous Chef — SaaS product site',
      tags: ['SaaS', 'Product site', 'UI/UX'],
      shot: '/images/portfolio/cards/sous-chef.webp',
      href: '/en/projects/sous-chef',
      category: 'systems',
    },
    {
      id: 'karin-cohen',
      title: 'Karin Cohen — lash academy',
      tags: ['Landing page', 'UI/UX', 'Lead capture', 'WhatsApp'],
      shot: '/images/portfolio/cards/karin-cohen.webp',
      href: '/en/projects/karin-cohen',
      category: 'brand',
    },
    {
      id: 'maayan-cosmetics',
      title: 'Maayan Vaknin — clinical cosmetics',
      tags: ['Landing page', 'UI/UX', 'Accessibility', 'Lead capture'],
      shot: '/images/portfolio/cards/maayan-cosmetics.webp',
      href: '/en/projects/maayan-cosmetics',
      category: 'brand',
    },
    {
      id: 'eli-ben-yitzhak',
      title: 'Eli Ben Yitzhak — hair design',
      tags: ['Landing page', 'UI/UX', 'Work gallery', 'WhatsApp'],
      shot: '/images/portfolio/cards/eli-ben-yitzhak.webp',
      href: '/en/projects/eli-ben-yitzhak',
      category: 'brand',
    },
    {
      id: 'brand-identity',
      title: 'Ram and Haim — real estate marketing',
      tags: ['SEO', 'Reputation', 'Digital assets'],
      shot: '/images/portfolio/cards/brand-identity.webp',
      href: '/en/projects/brand-identity',
      category: 'brand',
    },
    {
      id: 'marketing-platform',
      title: 'Avi — mortgage advisory',
      tags: ['Branding', 'Landing pages', 'Meta ads', 'Funnel'],
      shot: '/images/portfolio/cards/marketing-platform.webp',
      href: '/en/projects/marketing-platform',
      category: 'brand',
    },
    {
      id: 'ecommerce-store',
      title: 'Digital store',
      tags: ['Online store', 'Development', 'Payments'],
      shot: '/images/portfolio/shots/ecommerce-store.webp',
      href: '/en/projects/ecommerce-store',
      category: 'sales',
    },
    {
      id: 'alexandra-patsina',
      title: 'Alexandra Patsina',
      tags: ['Brand site', 'Branding', 'UI/UX'],
      shot: '/images/portfolio/shots/alexandra-patsina.webp',
      href: '/en/projects/alexandra-patsina',
      category: 'brand',
    },
  ],

  blog: {
    title: 'Blog',
    metaTitle: 'Blog - Guides on Web Development and SEO',
    metaDescription:
      'Practical guides and insights on custom web development, organic search, paid campaigns and business automation from the Aiterra team.',
    lede: 'Professional insight, practical guides and news from the world of digital. Our knowledge, for you.',
    crumbHome: 'Home',
    crumbsLabel: 'Breadcrumb',
    filters: [
      { id: 'all', label: 'All', tag: 'BLOG', match: [] as string[] },
      { id: 'seo', label: 'SEO', tag: 'SEO', match: ['SEO', 'search', 'Google'] },
      {
        id: 'sites',
        label: 'Websites',
        tag: 'WEBSITES',
        match: ['website', 'WordPress', 'Next.js', 'React', 'landing page'],
      },
      { id: 'tips', label: 'Guides', tag: 'TIPS', match: ['guide', 'automation', 'CRM', 'marketing'] },
    ],
    readTime: 'min read',
    readMore: 'Read the article',
    loadMore: 'Load more articles',
    defaultTag: 'BLOG',
    empty: 'No articles in this category yet.',
    defaultAuthor: 'The Aiterra team',
  },

  servicesStack: {
    eyebrow: 'OUR SERVICES',
    heading: ['Every capability under', 'one roof'],
    lede: 'We do not separate the engineering from the growth work. The team that ships your code is the team accountable for how it performs in search - which removes the handoff where most agency projects quietly stall.',
    items: [
      {
        id: 'web-development',
        title: 'Custom web development',
        image: '/images/service3.webp',
        tags: [
          'Discovery',
          'UX/UI design',
          'Next.js and React',
          'Core Web Vitals',
          'Accessibility',
          'Code ownership',
        ],
        text: 'Websites built in code around how your business actually sells - fast, accessible, and structured for organic search from day one. You own the repository.',
        action: { label: 'Learn more', href: '/en/services/web-development' },
      },
      {
        id: 'seo',
        title: 'SEO and website promotion',
        image: '/images/service-page2.webp',
        tags: [
          'Keyword research',
          'Technical SEO',
          'Content',
          'Digital PR',
          'Local search',
          'AI search visibility',
        ],
        text: 'Organic growth measured in qualified enquiries rather than positions. The same team writes the code, so technical blockers get fixed in the repository instead of a backlog.',
        action: { label: 'Learn more', href: '/en/services/seo' },
      },
      {
        id: 'ecommerce',
        title: 'Online stores',
        image: '/images/service1.webp',
        tags: [
          'Catalogue design',
          'Checkout',
          'Payments',
          'Inventory',
          'Order management',
          'Migration',
        ],
        text: 'Stores engineered in code rather than assembled from plugins - catalogue, checkout and the payment and invoicing integrations your business already runs on.',
        action: { label: 'Learn more', href: '/en/services/ecommerce' },
      },
      {
        id: 'development',
        title: 'Custom web platforms',
        image: '/images/service2.webp',
        tags: [
          'Web applications',
          'Customer portals',
          'Dashboards',
          'Automation',
          'API integrations',
          'Internal tools',
        ],
        text: 'Portals, dashboards, internal tools and the integrations between them - built for the workflows that off-the-shelf software cannot cover.',
        action: { label: 'Learn more', href: '/en/services/development' },
      },
      {
        id: 'marketing',
        title: 'Paid campaigns',
        image: '/images/service4.webp',
        tags: [
          'Google Ads',
          'Meta Ads',
          'Landing pages',
          'Creative',
          'Conversion tracking',
          'Reporting',
        ],
        text: 'Campaigns judged on cost per lead, with the landing page and the tracking built by the same team that runs the ads - so nothing is lost between the click and the enquiry.',
        action: { label: 'Learn more', href: '/en/services/marketing' },
      },
      {
        id: 'branding',
        title: 'Brand and UX/UI',
        image: '/images/service-branding.webp',
        tags: [
          'Brand identity',
          'Visual language',
          'UX/UI design',
          'Design systems',
          'Mobile apps',
          'Developer handoff',
        ],
        text: 'Identity and interface design delivered as a system with rules and states - made by a team that also has to build it, so the design survives implementation.',
        action: { label: 'Learn more', href: '/en/services/branding' },
      },
      {
        id: 'brochure',
        title: 'Business websites',
        image: '/images/service-dev.webp',
        tags: [
          'Positioning',
          'Page structure',
          'Copywriting',
          'Design',
          'Forms and leads',
          'Measurement',
        ],
        text: 'A business site whose job is to produce enquiries: positioning, structure, copy and design that lead the visitor to one clear action rather than to a brochure.',
        action: { label: 'Learn more', href: '/en/services/brochure' },
      },
      {
        id: 'maintenance',
        title: 'Website maintenance',
        image: '/images/services-view-bg.webp',
        tags: [
          'Published pricing',
          'Written SLA',
          'Security updates',
          'Backups and monitoring',
          'IS 5568 checks',
          'Israeli integrations',
        ],
        text: 'Monthly maintenance with published prices and response times written into the agreement - including for sites we did not build.',
        action: { label: 'Learn more', href: '/en/services/maintenance' },
      },
      {
        id: 'ai-agents',
        title: 'AI agents',
        image: '/images/service-agents-hero.webp',
        tags: [
          'Round-the-clock replies',
          'Lead qualification',
          'Meeting booking',
          'CRM connection',
          'WhatsApp',
          'Human handoff',
        ],
        text: 'AI agents that answer from your own content, act inside the systems you already run, and hand the conversation to a person at the point you defined in advance.',
        action: { label: 'Learn more', href: '/en/services/ai-agents' },
      },
      {
        id: 'ai-search',
        title: 'AI search visibility',
        image: '/images/service-ai-search-hero.webp',
        tags: [
          'AI Overviews',
          'ChatGPT and Gemini',
          'Entity definition',
          'Structured data',
          'Quotable content',
          'Visibility report',
        ],
        text: 'Getting cited in the answers engines write rather than the lists they used to return: entity and schema work, content built to be quoted, and a monthly report of where you are named and where you are not.',
        action: { label: 'Learn more', href: '/en/services/ai-search' },
      },
    ],
  },

  servicesPage: {
    title: ['End-to-end digital', 'engineering and growth'],
    crumb: 'Services',
    metaTitle: 'Custom Web Development, SEO and Platform Services',
    metaDescription:
      'Custom web development, SEO and bespoke web platforms from one in-house team. Full code ownership, measurable organic growth, no vendor lock-in.',
    lede: 'From the technical foundations through to paying customers. We provide a complete service layer sized to your business, built to turn every digital asset into a growth engine.',
    action: { label: 'Start a project', href: '/en/contact' },
    faqHeading: ['Frequently asked questions', 'about our services'],
  },

  contactPage: {
    title: 'Let us talk',
    crumb: 'Contact',
    lede: 'From technical foundations through to paying customers - we would like to hear about your business. Leave your details and we will come back with a tailored plan of action.',
    metaTitle: 'Contact Aiterra - Free Initial Consultation',
    metaDescription:
      'Planning a custom website, a web platform or an SEO programme? Leave your details and we will respond with a tailored plan and transparent pricing.',
    faqHeading: ['Frequently asked questions', 'before you get in touch'],
    details: {
      heading: 'Contact details',
      mapTitle: 'Aiterra office location',
      emailLabel: 'Email us',
      phoneLabel: 'Call us',
      addressLabel: 'Our address',
      maps: 'Open the address in Google Maps',
      waze: 'Navigate with Waze',
    },
  },

  aboutPage: {
    title: 'About us',
    metaTitle: 'About Aiterra - Engineering and Growth in One Team',
    metaDescription:
      'Aiterra is a custom web development and SEO agency. Meet the team, the working method and the experience behind hundreds of delivered projects.',
    lede: 'Digital moves fast. We make sure you stay a step ahead of it.',
    eyebrow: 'ABOUT Aiterra',
    heading: ['Technology that builds websites.', 'Strategy that builds businesses.'],
    paragraphs: [
      'Aiterra closes the gap between complex technology and results a business can actually measure.',
      'From strategy and UX through scalable platform engineering, organic search and paid campaigns, we turn your digital presence into a growth engine rather than a line item.',
    ],
    blocks: [
      {
        id: 'about',
        eyebrow: 'ABOUT Aiterra',
        heading: ['Moving businesses', 'two steps ahead'],
        text: 'With Aiterra there is no need to chase a different vendor for every stage. Discovery, design, engineering, organic search, paid campaigns and content sit with one team that owns the whole process. The result is a smoother project, direct communication, and a complete digital solution that actually moves the numbers.',
        image: '/images/about-page1.webp',
      },
      {
        id: 'strategy',
        eyebrow: 'OUR STRATEGY',
        heading: ['From strategy to results'],
        text: 'We do not just build websites - we support businesses at every stage of their digital presence. From user experience and engineering through organic search and campaign management, every decision is tied back to a commercial goal that was agreed before the work started.',
        image: '/images/about-page2.webp',
      },
    ],
    teamEyebrow: 'OUR PEOPLE',
    teamHeading: ['The people behind the technology', 'and behind your results'],
    teamLede: 'The best technology in the world is worth very little without the right people running it. We keep a small, senior team where the person who scopes your project is the person accountable for delivering it.',
    teamMore: 'More about',
    teamClose: 'Close',
    faqHeading: ['Frequently asked questions', 'why work with Aiterra?'],
  },

  aboutValues: {
    eyebrow: 'OUR VALUES',
    heading: ['Our values and vision'],
    lede: 'The principles that guide how we work with every client and every project we take on.',
    roles: [
      {
        id: 'people',
        title: 'People first',
        art: '/images/about-icon1.webp',
        text: 'Behind every project are people - your customers, your visitors and our team. We listen, clarify, and build solutions that genuinely serve them.',
      },
      {
        id: 'strategy',
        title: 'Strategy',
        art: '/images/about-icon2.webp',
        text: 'Before a line of code or a campaign there is a plan: defined goals, a defined audience and a way to measure. That is how each step actually moves the business.',
      },
      {
        id: 'excellence',
        title: 'Craft',
        art: '/images/about-icon3.webp',
        text: 'We do not compromise on quality in code, in design or in outcomes. Every project goes through rigorous review before it ships.',
      },
      {
        id: 'progress',
        title: 'Progress',
        art: '/images/about-icon4.webp',
        text: 'Digital does not stand still, and neither do we. We adopt new technology when it measurably improves the result, not because it is new.',
      },
    ],
  },
}

export const projectsPageEn = {
  title: ['Our work', 'Selected projects'],
  crumb: 'Work',
  lede: 'Twelve live projects: three online stores, marketing and lead-generation sites across cosmetics and personal brands, and work in real estate and mortgage advisory. All written in code by the same team that promotes them, and all in production today.',
  action: { label: 'Start a project', href: '/en/contact' },
  faqHeading: ['Before we start', 'a few things worth knowing.'],
  metaTitle: 'Our Work - 12 Sites, Stores and Systems We Built',
  metaDescription:
    'Twelve live Aiterra projects: online stores, lead-generation sites and management systems, all built in code. See the goal, the integrations and what shipped.',
}
