import type { V2ContentKey } from '@/app/v2/content'

export type SectionMeta = {
  key: V2ContentKey
  label: string
  hint: string
  preview: string
}

export type SectionGroup = {
  id: string
  label: string
  sections: SectionMeta[]
}

export const SECTION_GROUPS: SectionGroup[] = [
  {
    id: 'global',
    label: 'כללי',
    sections: [
      { key: 'header', label: 'תפריט עליון', hint: 'לוגו, ניווט וכפתור הצעת מחיר', preview: '/v2' },
      { key: 'footer', label: 'פוטר', hint: 'עמודות קישורים, יצירת קשר וזכויות', preview: '/v2' },
      { key: 'legal', label: 'עמודים משפטיים', hint: 'טקסטים קבועים בעמודי תקנון ונגישות', preview: '/v2/terms-of-use' },
    ],
  },
  {
    id: 'home',
    label: 'דף הבית',
    sections: [
      { key: 'hero', label: 'Hero — כותרת ראשית', hint: 'כותרת, תגיות, פסקה וכפתורים', preview: '/v2' },
      { key: 'heroRails', label: 'Hero — כותרות הפסים', hint: 'כותרות פס הפרויקטים ופס התחומים', preview: '/v2' },
      { key: 'heroProjects', label: 'Hero — פס פרויקטים', hint: 'הפרויקטים שרצים בפס הימני', preview: '/v2' },
      { key: 'heroTopics', label: 'Hero — פס תחומים', hint: 'תגיות התחומים שרצות בפס', preview: '/v2' },
      { key: 'about', label: 'אודות (בדף הבית)', hint: 'כותרת, פסקה וטקסט סיום', preview: '/v2#v2-about-heading' },
      { key: 'aboutRoles', label: 'אודות — כרטיסי בעלי מקצוע', hint: 'ארבעת הכרטיסים בסקשן אודות', preview: '/v2' },
      { key: 'stats', label: 'נתונים — כותרת', hint: 'כותרת ופסקה של סקשן הנתונים', preview: '/v2' },
      { key: 'statItems', label: 'נתונים — מספרים', hint: 'הערכים, התוויות והטקסטים', preview: '/v2' },
      { key: 'services', label: 'שירותים — כותרת', hint: 'כותרת, פסקה ורצועת ה-CTA', preview: '/v2#v2-services' },
      { key: 'serviceTabs', label: 'שירותים — טאבים', hint: 'חמשת הטאבים עם התגיות והפסקאות', preview: '/v2#v2-services' },
      { key: 'portfolio', label: 'תיק עבודות — כותרת', hint: 'כותרת, פסקה, כפתורים וטקסט סיום', preview: '/v2#v2-portfolio' },
      { key: 'portfolioFilters', label: 'תיק עבודות — פילטרים', hint: 'תוויות הקטגוריות (מופיעות גם בתפריט)', preview: '/v2#v2-portfolio' },
      { key: 'portfolioItems', label: 'תיק עבודות — פרויקטים', hint: 'הכרטיסים בקרוסלה', preview: '/v2#v2-portfolio' },
      { key: 'projectPage', label: 'עמוד פרויקט — תוויות', hint: 'כותרות, פירורי לחם וטבלת הפרטים בעמוד פרויקט', preview: '/v2/projects/neot-sade' },
      { key: 'projectBanner', label: 'עמוד פרויקט — רצועת CTA', hint: 'הכותרת והכפתור ברצועה שלפני "פרויקטים נוספים"', preview: '/v2/projects/neot-sade' },
      { key: 'allIn', label: 'All-in-one — כותרת', hint: 'כותרת סקשן התרשים', preview: '/v2' },
      { key: 'allInNodes', label: 'All-in-one — נקודות', hint: 'תוויות הנקודות (המיקומים בשדות טכניים)', preview: '/v2' },
      { key: 'partners', label: 'טכנולוגיות ושותפים', hint: 'כיתוב ולוגואים', preview: '/v2' },
      { key: 'reels', label: 'קריאייטיב — כותרת', hint: 'כותרת ופסקה של סקשן הרילים', preview: '/v2' },
      { key: 'reelItems', label: 'קריאייטיב — רילים', hint: 'תוויות הרילים בקרוסלה', preview: '/v2' },
      { key: 'reviews', label: 'ביקורות — כותרת', hint: 'כותרת, פסקה ותוויות ניווט', preview: '/v2' },
      { key: 'reviewItems', label: 'ביקורות — תוכן', hint: 'ביקורות הלקוחות (טקסט מודגש = accent)', preview: '/v2' },
      { key: 'clientStories', label: 'סיפורי לקוחות — כותרת', hint: 'הקרוסלה השנייה בדף הבית', preview: '/v2' },
      { key: 'clientStoryItems', label: 'סיפורי לקוחות — פריטים', hint: 'תוויות הסרטונים', preview: '/v2' },
      { key: 'faq', label: 'שאלות נפוצות — כותרת', hint: 'כותרת סקשן ה-FAQ בדף הבית', preview: '/v2' },
      { key: 'faqEntries', label: 'שאלות נפוצות — שאלות', hint: 'שאלות ותשובות בדף הבית', preview: '/v2' },
    ],
  },
  {
    id: 'about',
    label: 'עמוד אודות',
    sections: [
      { key: 'aboutPage', label: 'אודות — עמוד', hint: 'כותרות, בלוקים, צוות ו-FAQ', preview: '/v2/about' },
      { key: 'aboutValues', label: 'אודות — ערכים', hint: 'סקשן הערכים והחזון', preview: '/v2/about' },
    ],
  },
  {
    id: 'services',
    label: 'שירותים',
    sections: [
      { key: 'servicesPage', label: 'שירותים — עמוד', hint: 'כותרת, פסקה, כפתור ו-SEO', preview: '/v2/services' },
      { key: 'servicesStack', label: 'שירותים — כרטיסים', hint: 'ארבעת הכרטיסים (מופיעים גם בתפריט)', preview: '/v2/services' },
      { key: 'servicePages', label: 'עמודי שירות פנימיים', hint: 'כל התוכן של עמוד שירות בודד', preview: '/v2/services/ecommerce' },
    ],
  },
  {
    id: 'blog',
    label: 'בלוג',
    sections: [
      { key: 'blog', label: 'בלוג — עמוד', hint: 'כותרת, פילטרים ותוויות', preview: '/v2/blog' },
      { key: 'article', label: 'מאמר — תוויות', hint: 'תוכן עניינים, שיתוף, מאמרים קשורים', preview: '/v2/blog' },
    ],
  },
  {
    id: 'contact',
    label: 'יצירת קשר',
    sections: [
      { key: 'contact', label: 'טופס יצירת קשר', hint: 'שדות, הסכמה, הודעות הצלחה ושגיאה', preview: '/v2/contact' },
      { key: 'contactPage', label: 'עמוד יצירת קשר', hint: 'כותרת העמוד ופרטי ההתקשרות', preview: '/v2/contact' },
    ],
  },
]

export const SECTION_INDEX: Record<string, SectionMeta> = Object.fromEntries(
  SECTION_GROUPS.flatMap((group) => group.sections).map((section) => [section.key, section]),
)

export const FIELD_LABELS: Record<string, string> = {
  action: 'כפתור',
  advantages: 'סקשן יתרונות',
  after: 'טקסט אחרי',
  answer: 'תשובה',
  art: 'תמונה',
  audience: 'למי מתאים',
  author: 'שם הלקוח',
  authorLabel: 'תווית כותב',
  badge: 'תגית על הכרטיס',
  banner: 'רצועת CTA',
  before: 'טקסט לפני',
  blocks: 'בלוקים',
  body: 'תוכן',
  brand: 'שם המותג',
  caption: 'כיתוב',
  cardAction: 'טקסט כפתור בכרטיס',
  collapse: 'תווית סגירה',
  columns: 'עמודות',
  consent: 'הסכמה לתנאים',
  contactTitle: 'כותרת יצירת קשר',
  copied: 'הודעת העתקה',
  copyright: 'זכויות יוצרים',
  crumb: 'פירור לחם',
  crumbHome: 'פירור — בית',
  crumbsLabel: 'תווית נגישות לפירורים',
  cta: 'כפתור ראשי',
  defaultAuthor: 'כותב ברירת מחדל',
  defaultTag: 'תגית ברירת מחדל',
  details: 'פרטי התקשרות',
  email: 'מייל',
  emailLabel: 'תווית מייל',
  empty: 'הודעה כשאין תוצאות',
  error: 'הודעת שגיאה',
  expand: 'תווית פתיחה',
  eyebrow: 'כותרת עליונה',
  faqEntries: 'שאלות ותשובות',
  faqHeading: 'כותרת שאלות נפוצות',
  features: 'יכולות',
  featuresTitle: 'כותרת רשימת היכולות',
  fields: 'שדות הטופס',
  filters: 'פילטרים',
  footnote: 'הערת שוליים',
  headline: 'כותרת ראשית',
  heading: 'כותרת',
  href: 'קישור',
  howItWorks: 'סקשן איך זה עובד',
  image: 'תמונה',
  joiner: 'מחבר',
  label: 'תווית',
  lede: 'פסקת פתיחה',
  legal: 'קישורים משפטיים',
  link: 'קישור',
  links: 'קישורים',
  loadMore: 'טעינת עוד',
  logos: 'לוגואים',
  mapTitle: 'תווית מפה',
  maps: 'תווית Google Maps',
  menuClose: 'תווית סגירת תפריט',
  menuOpen: 'תווית פתיחת תפריט',
  message: 'הודעה',
  metaDescription: 'תיאור SEO',
  metaTitle: 'כותרת SEO',
  mobileNavLabel: 'תווית ניווט נייד',
  name: 'שם',
  nav: 'פריטי ניווט',
  navLabel: 'תווית ניווט ראשי',
  next: 'כפתור הבא',
  outro: 'טקסט סיום',
  paragraphs: 'פסקאות',
  phone: 'טלפון',
  phoneLabel: 'תווית טלפון',
  plans: 'מסלולים',
  premium: 'פרימיום',
  prev: 'כפתור הקודם',
  price: 'מחיר',
  priceNote: 'הערת מחיר',
  pricing: 'סקשן מחירים',
  primaryAction: 'כפתור ראשי',
  privacy: 'מדיניות פרטיות',
  projectsAdvance: 'תווית מעבר לפרויקט',
  projectsTitle: 'כותרת פס הפרויקטים',
  promoLabel: 'תווית באנר צדדי',
  publishedPrefix: 'קידומת תאריך פרסום',
  question: 'שאלה',
  rail: 'תווית הקרוסלה',
  rating: 'דירוג',
  readMore: 'קריאת המשך',
  readTime: 'זמן קריאה',
  relatedTitle: 'כותרת מאמרים קשורים',
  roles: 'כרטיסים',
  secondaryAction: 'כפתור משני',
  sending: 'טקסט בזמן שליחה',
  serviceOther: 'אפשרות "אחר"',
  servicePlaceholder: 'טקסט ברירת מחדל בבחירה',
  share: 'תווית שיתוף',
  social: 'רשתות חברתיות',
  socialLabels: 'תוויות רשתות חברתיות',
  steps: 'שלבים',
  subhead: 'כותרת משנה',
  submit: 'כפתור שליחה',
  success: 'הודעת הצלחה',
  system: 'סקשן מערכת הניהול',
  tags: 'תגיות',
  teamClose: 'תווית סגירה',
  teamEyebrow: 'צוות — כותרת עליונה',
  teamHeading: 'צוות — כותרת',
  teamLede: 'צוות — פסקה',
  teamMore: 'צוות — טקסט "עוד על"',
  term: 'תקופת חיוב',
  terms: 'תנאי שימוש',
  text: 'טקסט',
  title: 'כותרת',
  tocTitle: 'כותרת תוכן עניינים',
  topicsAdvance: 'תווית מעבר לתחומים',
  topicsTitle: 'כותרת פס התחומים',
  updatedPrefix: 'קידומת "עודכן לאחרונה"',
  value: 'ערך',
  waze: 'תווית Waze',
  when: 'מתי',
}

export const ADVANCED_KEYS = new Set([
  'category',
  'edge',
  'featured',
  'icon',
  'id',
  'len',
  'match',
  'mobile',
  'place',
  'scale',
  'side',
  'submenu',
  'surface',
  'tint',
  'x',
  'y',
])

export const IMAGE_KEYS = new Set(['art', 'avatar', 'image', 'images', 'shot', 'src'])

export const LONG_TEXT_KEYS = new Set([
  'answer',
  'bio',
  'lede',
  'metaDescription',
  'outro',
  'text',
  'teamLede',
])
